### PR TITLE
fix: Now all Statement classes can be used with this interface

### PR DESCRIPTION
**Pull request by faustimetal**

### CODE REVIEW

**Comment by mschering** [comment]
This breaks PHP 7.3 compatibility.

**Comment by faustimetal** [comment]
> This breaks PHP 7.3 compatibility.

"setStatementClass($statementClass): self and related functionality" is useless for other classes than the default class without it.

**Comment by twitnic** [comment]
The tests are green. With 7.3 https://github.com/sandermarechal/jejik-mt940/runs/5306107930?check_suite_focus=true

Do we also have a failure in our tests?

**Comment by mschering** [comment]
The specific error I was getting:

...vendor/jejik/mt940/lib/Jejik/MT940/Parser/Rabobank.php at line 24: Declaration of Jejik\\MT940\\Parser\\Rabobank::statementBody(string $text): Jejik\\MT940\\Statement must be compatible with Jejik\\MT940\\Parser\\AbstractParser::statementBody(string $text): ?Jejik\\MT940\\StatementInterface, ...

You can only do this from php 7.4 and higher.

**Comment by twitnic** [comment]
closed in 0.5.15

**Comment by mschering** [comment]
Great! Thank you for the fast fix!

**Comment by faustimetal** [comment]
This broke compability with 7.4 and upwards. The only fix for this is removing de typehinting all together.

**Comment by twitnic** [comment]
@faustimetal You are right. Sometimes is enterprise software a little bit late ...
But we could move to php 7.4.

7.3 is no more supported. I create a new Release. with requirement 7.4 | 8. But before I would test it ...
Give me 2 Days :)

**Pull request merged**
